### ISSUE TITLE
ljn.driver() causes TypeError exception

### ISSUE THREAD

**Issue by jupe** [chrisJohn404/LabJack-nodejs#14]
What might be wrong if this kind of exception happens?

```
> var ljn = require('labjack-nodejs');
undefined
> var driver = ljn.driver();
TypeError: Cannot read property 'length' of undefined
    at Object.syncLJMFunction [as LJM_ReadLibraryConfigS] (/home/X/labjack-nodejs/node_modules/ljm-ffi/lib/ljm-ffi.js:733:49)
    at Object.<anonymous> (/home/X/labjack-nodejs/lib/driver_wrapper.js:25:33)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

I'm trying to use U3 in ubuntu. drivers should work, at least examples as well as python labjack library. With this node binding doesn't :/ Before this it crash to exception about missing `/usr/local/share/LabJack/LJM/ljm_constants.json` -file, but after I copied that file it goes further, but not success yet..

**Comment by jupe** [comment]
I realized that README says that U3 is not supported, damn. So this issue can be closed probably. Anyway do you know if there is node module which support U3 ?

**Comment by rolsen** [comment]
Hello @jupe. Apologies, but there is no Node module which supports the U3, but there are a few [other options](https://labjack.com/support/software/examples/ud). [LabJackPython](https://github.com/labjack/LabJackPython) probably has the most friendly API.
