### ISSUE TITLE
Failed to link function warnings

### ISSUE THREAD

**Issue by sofroniewn** [chrisJohn404/LabJack-nodejs#16]
I had labjack-nodejs v0.0.52 working great a while back using node v0.12.7, but have since upgraded to node v4.5.0 (and probably changed a couple more things I am unaware of) and have been running into some problems creating and opening devices that I can't solve. Do you think the different node version could make a difference? I am using a mac.

I installed labjack-nodejs as below
```
$ npm install labjack-nodejs

> ref@1.3.2 install /Users/sofroniewn/github/hardware-stream/node_modules/labjack-nodejs/node_modules/ref
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/binding.node

> ffi@2.1.0 install /Users/sofroniewn/github/hardware-stream/node_modules/labjack-nodejs/node_modules/ljm-ffi/node_modules/ffi
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/ffi_bindings.node
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
labjack-nodejs@0.0.54 node_modules/labjack-nodejs
├── ljswitchboard-ljm_driver_constants@0.0.28
├── q@1.4.1
├── async@0.9.2
├── ljswitchboard-modbus_map@0.0.16 (ljmmm-parse@0.1.9)
├── ref@1.3.2 (bindings@1.2.1, nan@2.4.0, debug@2.2.0)
└── ljm-ffi@1.0.5 (extend@3.0.0, ffi@2.1.0)
```

The install completes, but now when I try and create and open a device using the following code I get the messages bellow.
```
var ljn = require('labjack-nodejs')
var createDeviceObject = ljn.getDevice()
var board = new createDeviceObject()
board.openSync()
```

```
Warning: Failed to link function LJM_eReadAddressByteArray
Warning: Failed to link function LJM_eReadNameByteArray
Warning: Failed to link function LJM_eWriteAddressByteArray
Warning: Failed to link function LJM_eWriteNameByteArray
Warning: Failed to link function LJM_StreamBurst
Warning: Failed to link function LJM_GetSpecificIPsInfo
Warning: Failed to link function LJM_CleanInfo
Warning: Failed to link function Internal_LJM_OpenAll
Warning: Failed to link function Internal_LJM_GetHandles
ljmLibraryVersion 1.0808

/Users/sofroniewn/github/hardware-stream/node_modules/labjack-nodejs/lib/device.js:1526
					throw new DriverInterfaceError("Invalid Address");
					^
Driver Interface Error - device: Invalid Address
```

I have my hardware properly connected as if I go back and rerun my old code from labjack-nodejs v0.0.52 with node v0.12.7 then everything works just fine.

Any thoughts on why the linking has failed, and if those warnings are leading to the error?

Thanks
Nick

**Comment by chrisJohn404** [comment]
Nick,

When switching versions of node you definitely need to re-build all native modules.  I usually just delete the entire node_modules folder "rm -r node_modules" and then perform the "npm install" command again. This library is mostly dependent on ffi/ref in terms of node.js version compatibility.  I believe those libraries work just fine with 0.10.x, 0.12.x, 4.x, 5.x, and 6.x.  

The warnings shouldn't be an issue.  I should probably disable those warning statements in the ljm-ffi library.  I should also post a new version of the LabJack-nodejs library that doesn't have the "ljmLibraryVersion" print statement however it does look like you are using an old version of LJM.  The latest versions are 1.1200 and 1.1300 (beta).  

Judging by the error, it looks like you successfully opening a device and then you are executing the "writeSync" function.  The error is being thrown on line 1526.  This error isn't thrown during the openSync function.  You should check to make sure that the register you are trying to write to is a writable address.  

Can you double check your code and see if you are calling the writeSync function and what you are passing to it?

**Comment by chrisJohn404** [comment]
I just published the two libraries w/o the print statements to npm.  One other thing that I noticed was the openSync function wasn't returning an LJM error code if a device didn't get connected during the open call.  I don't think it was related to your issue.

Depending on what register you are trying to write to, the issue may be in the ljswitchboard-modbus_map dependency which is used to parse the .json file that defines all of the registers that can be read/written to for the T7.

**Comment by sofroniewn** [comment]
@chrisJohn404 thanks for the tips - and removing those warnings - all has been figured out now and is working great. I think there was a combination of my confusion with the version changes and a misuse of writeSync instead of writeManySync somewhere else in my code that I hadn't caught and was causing that error. Sorry for troubling you with this. I'm going to close the issue. I really like using the labjack with node, so thanks for making the library!
