### ISSUE TITLE
openSync broken

### ISSUE THREAD

**Issue by sampottinger** [chrisJohn404/LabJack-nodejs#8]
Hello!

It looks like openSync is broken but you can swap line 231 in device.js from

> var aDeviceHandle = new ref.alloc(ref.types.int,1);

to

> var refDeviceHandle = new ref.alloc(ref.types.int,1);

**Comment by RIAEvangelist** [comment]
openSync is working fine for me. Is there any more information on your node version etc. that you can provide to show why this is needed?

**Comment by RIAEvangelist** [comment]
just realized this is super old and can probably be closed.
